### ISSUE TITLE
Uncaught An unsuccessful status code was returned by the PHP side!

### ISSUE THREAD

**Issue by kerwynrg** [tocjent/php-integrator-symbol-viewer#2] opened 2016-01-28 18:54 UTC
Sometimes when I open a file shows the error below, and doesn't show tree viewer for the class

While this happens, it keeps working on some other files.

When I disable this package the error stop appearing, so that's why I'm reporting it here even when error is thrown in php-integrator-base

**Atom Version**: 1.4.1
**System**: Mac OS X 10.11.3
**Thrown From**: [php-integrator-base](https://github.com/Gert-dev/php-integrator-base) package, v0.4.8

### Stack Trace

Uncaught An unsuccessful status code was returned by the PHP side!

```
At /Users/Developer/.atom/packages/php-integrator-base/lib/Proxy.coffee:71

undefined
```

### Commands

```
     -9:02.5.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -9:01.2.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -9:01.2.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -9:00.6.0 settings-view:open (atom-text-editor.editor.is-focused)
  4x -8:54.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -8:51.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -8:43.1.0 core:cancel (div.package-readme.native-key-bindings)
     -0:07.8.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:06.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -0:05.3.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:04.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-autocomplete-php"
    ],
    "projectHome": "~/Projects",
    "themes": [
      "atom-material-ui",
      "one-dark-syntax"
    ]
  },
  "php-integrator-base": {}
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.5.1
atom-beautify, v0.28.21
atom-material-ui, v0.8.0
autoclose-html, v0.20.0
autocomplete-php, v0.3.7
docblockr, v0.7.3
drunken-php, v0.2.1
editorconfig, v1.2.4
file-icons, v1.6.14
highlight-selected, v0.11.1
language-javascript-jsx, v0.3.7
linter, v1.11.3
linter-eslint, v6.0.0
linter-js-yaml, v1.2.5
linter-jsonlint, v1.1.4
linter-php, v1.1.6
minimap, v4.19.0
minimap-cursorline, v0.1.0
minimap-find-and-replace, v4.4.0
minimap-highlight-selected, v4.3.1
minimap-selection, v4.3.1
package-sync, v1.0.0
php-cs-fixer, v2.5.2
php-integrator-annotations, v0.2.3
php-integrator-autocomplete-plus, v0.4.0
php-integrator-base, v0.4.8
php-integrator-navigation, v0.3.0
php-integrator-symbol-viewer, v0.1.1
php-integrator-tooltips, v0.3.0
php-twig, v4.0.0
pigments, v0.22.1
project-manager, v2.7.5
react-snippets, v0.3.0
set-syntax, v0.3.0
sync-settings, v0.6.0

# Dev
No dev packages
```

**Comment by tocjent** [comment] 2016-01-29 03:29
Hi, thanks for taking time to report this.

I believe the issue is a duplicate of #1.

In 0.2.0 release I fixed this by checking if active pane item is an instance of TextEditor. Updating should fix the issue.

**Closed by tocjent** 2016-01-29 03:29 UTC
Labels: duplicate
